apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata: 
      name: mongo-pod
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          #args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: useraname
                  name: mongo-config
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-secret              
        
