apiVersion: v1
kind: Service
metadata: 
  name: mongo-service
spec:
  selector:
    app: mongo-app
  type: NodePort
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32000