# emptyDir is persistant volume at POD LEVEL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-emptydir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata: 
      name: mongo-pod
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          emptyDir: {} # pod level volume
              
        
