apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  type: NodePort
  selector:
    app: mongo-app
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000 
