apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-deployment
  labels: 
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: venu1322/django-web-app:0.0.1.RELEASE
      # volume mount
        volumeMounts:
        - name: db-secrets
          mountPath: "/opt/db-secrets"
        ports:
        - containerPort: 8000
      #volume creation
      volumes:
      - name: db-secrets
        secret:
         secretName: secret-deploy