apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels: 
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: venu1322/django-web-app:0.0.1.RELEASE
        ports:
        - containerPort: 8000