apiVersion: v1
kind: Pod
metadata: 
  name: resources-requests
spec:
  containers:
    - name: resources-demo
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "1", "--vm-hang", "1"]
      resources:
        requests:
          cpu: "200m"
          memory: "1Gi"
        