apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-config
immutable: false
data:
  username: admin
  # password: pass
  mongodb.conf: |
    storage:
      dbPath: /data/venu
    replication:
      replSetName: "rs0"
