apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: nginx-ingress
spec:
  tls:
    - secretName: django-demo-com-tls
      hosts:
        - "django-demo.com"
  rules:
    - host: django-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-service
                port:
                  number: 8000